/**
 * Typed browser client for the reconciliation endpoints.
 *
 * Every call carries the Supabase access token, matching the rest of the app.
 * Errors come back as the plain sentence the server chose, so the UI can render
 * `error.message` directly without inventing its own wording.
 */

import type { SessionView } from "../server/session-view";

export type { SessionView } from "../server/session-view";
export type {
  SessionViewExpense,
  SessionViewLine,
  SessionViewPage,
} from "../server/session-view";

export class ReconciliationApiError extends Error {
  readonly status: number;

  constructor(message: string, status: number) {
    super(message);
    this.name = "ReconciliationApiError";
    this.status = status;
  }
}

const GENERIC_FAILURE = "Hallix could not reach the server. Check your connection and try again.";

type ApiOptions = { token: string; signal?: AbortSignal };

async function request<T>(
  url: string,
  init: RequestInit,
  token: string,
): Promise<T> {
  let response: Response;
  try {
    response = await fetch(url, {
      ...init,
      headers: { ...(init.headers || {}), Authorization: `Bearer ${token}` },
    });
  } catch (error) {
    if (error instanceof DOMException && error.name === "AbortError") throw error;
    throw new ReconciliationApiError(GENERIC_FAILURE, 0);
  }

  let payload: { ok?: boolean; error?: string } & Record<string, unknown>;
  try {
    payload = await response.json();
  } catch {
    throw new ReconciliationApiError(GENERIC_FAILURE, response.status);
  }

  if (!response.ok || payload.ok === false) {
    throw new ReconciliationApiError(
      typeof payload.error === "string" && payload.error ? payload.error : GENERIC_FAILURE,
      response.status,
    );
  }

  return payload as T;
}

function jsonInit(method: string, body: unknown, signal?: AbortSignal): RequestInit {
  return {
    method,
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
    signal,
  };
}

export async function startSession(
  options: ApiOptions & { departmentId: string; bankAccountId: string; resumeExisting?: boolean },
): Promise<{ resumed: boolean; view: SessionView }> {
  return request(
    "/api/reconciliation/sessions",
    jsonInit(
      "POST",
      {
        departmentId: options.departmentId,
        bankAccountId: options.bankAccountId,
        resumeExisting: options.resumeExisting ?? true,
      },
      options.signal,
    ),
    options.token,
  );
}

export async function getSession(
  options: ApiOptions & { sessionId: string; departmentId: string },
): Promise<{ view: SessionView }> {
  const query = new URLSearchParams({ departmentId: options.departmentId });
  return request(
    `/api/reconciliation/sessions/${options.sessionId}?${query}`,
    { method: "GET", signal: options.signal },
    options.token,
  );
}

export async function abandonSession(
  options: ApiOptions & { sessionId: string; departmentId: string },
): Promise<{ abandoned: boolean }> {
  const query = new URLSearchParams({ departmentId: options.departmentId });
  return request(
    `/api/reconciliation/sessions/${options.sessionId}?${query}`,
    { method: "DELETE", signal: options.signal },
    options.token,
  );
}

export type UploadPageResult = {
  page: {
    clientPageId: string;
    pageOrder: number;
    status: "complete" | "unreadable" | "failed";
    statusDetail: string | null;
    lineCount: number;
    printedPageNumber: number | null;
    printedPageCount: number | null;
    warnings: string[];
  };
};

/**
 * Send one prepared page for extraction.
 *
 * `clientPageId` is generated by the browser and is what makes a retry safe: the
 * server upserts on it, so re-sending a page that timed out replaces the earlier
 * attempt instead of adding a second copy.
 */
export async function uploadPage(
  options: ApiOptions & {
    sessionId: string;
    departmentId: string;
    clientPageId: string;
    pageOrder: number;
    totalPages: number;
    blob: Blob;
    fileName: string;
  },
): Promise<UploadPageResult> {
  const form = new FormData();
  form.append("departmentId", options.departmentId);
  form.append("clientPageId", options.clientPageId);
  form.append("pageOrder", String(options.pageOrder));
  form.append("totalPages", String(options.totalPages));
  form.append("page", options.blob, options.fileName);

  return request(
    `/api/reconciliation/sessions/${options.sessionId}/pages`,
    { method: "POST", body: form, signal: options.signal },
    options.token,
  );
}

export async function deletePage(
  options: ApiOptions & { sessionId: string; departmentId: string; clientPageId: string },
): Promise<{ view: SessionView }> {
  const query = new URLSearchParams({
    departmentId: options.departmentId,
    clientPageId: options.clientPageId,
  });
  return request(
    `/api/reconciliation/sessions/${options.sessionId}/pages?${query}`,
    { method: "DELETE", signal: options.signal },
    options.token,
  );
}

/** Wipe every page on a draft so a new PDF/photo set can be uploaded cleanly. */
export async function clearAllPages(
  options: ApiOptions & { sessionId: string; departmentId: string },
): Promise<{ view: SessionView }> {
  const query = new URLSearchParams({
    departmentId: options.departmentId,
    clearAll: "1",
  });
  return request(
    `/api/reconciliation/sessions/${options.sessionId}/pages?${query}`,
    { method: "DELETE", signal: options.signal },
    options.token,
  );
}

export async function consolidateSession(
  options: ApiOptions & {
    sessionId: string;
    departmentId: string;
    manualBeginningBalance?: string | null;
    manualEndingBalance?: string | null;
    manualStatementStartDate?: string | null;
    manualStatementEndDate?: string | null;
  },
): Promise<{ view: SessionView }> {
  const body: Record<string, unknown> = { departmentId: options.departmentId };
  if (options.manualBeginningBalance !== undefined) {
    body.manualBeginningBalance = options.manualBeginningBalance;
  }
  if (options.manualEndingBalance !== undefined) {
    body.manualEndingBalance = options.manualEndingBalance;
  }
  if (options.manualStatementStartDate !== undefined) {
    body.manualStatementStartDate = options.manualStatementStartDate;
  }
  if (options.manualStatementEndDate !== undefined) {
    body.manualStatementEndDate = options.manualStatementEndDate;
  }

  return request(
    `/api/reconciliation/sessions/${options.sessionId}/consolidate`,
    jsonInit("POST", body, options.signal),
    options.token,
  );
}

export type LineAction = "match" | "unmatch" | "not_applicable" | "correct" | "reset";

export type LineCorrectionPayload = {
  postedDate?: string | null;
  originalDescription?: string | null;
  signedAmount?: string | number | null;
  checkNumber?: string | null;
  referenceNumber?: string | null;
};

export async function patchLine(
  options: ApiOptions & {
    sessionId: string;
    lineId: string;
    departmentId: string;
    action: LineAction;
    expenseId?: string | null;
    correction?: LineCorrectionPayload;
  },
): Promise<{ view: SessionView }> {
  return request(
    `/api/reconciliation/sessions/${options.sessionId}/lines/${options.lineId}`,
    jsonInit(
      "PATCH",
      {
        departmentId: options.departmentId,
        action: options.action,
        expenseId: options.expenseId ?? undefined,
        correction: options.correction,
      },
      options.signal,
    ),
    options.token,
  );
}

export async function confirmReconciliation(
  options: ApiOptions & {
    sessionId: string;
    departmentId: string;
    lineIds: string[];
    overrideReason?: string | null;
  },
): Promise<{
  alreadyConfirmed: boolean;
  confirmedCount: number;
  confirmedAt: string | null;
  view: SessionView;
}> {
  return request(
    `/api/reconciliation/sessions/${options.sessionId}/confirm`,
    jsonInit(
      "POST",
      {
        departmentId: options.departmentId,
        lineIds: options.lineIds,
        overrideReason: options.overrideReason ?? null,
      },
      options.signal,
    ),
    options.token,
  );
}
