"use client";

/**
 * AI Insights.
 *
 * Every insight is produced by a deterministic rule in lib/analytics/insights.ts
 * and carries the exact figures it was generated from. The optional OpenAI pass
 * only rewrites that verified wording into plainer prose — it never sees the
 * ledger, never computes a total, and never adds a claim. If it is unavailable
 * or returns anything unexpected, the deterministic text stands.
 *
 * The dashboard only ever shows the top three by default. Everything else —
 * the full explanation, citations, and the rest of the list — lives behind a
 * click, so the page communicates what needs attention without reading like a
 * report.
 */

import { useEffect, useRef, useState } from "react";

import { INSIGHT_SEVERITY_LABELS, insightNarrationPayload, type Insight } from "../../lib/analytics/insights";
import type { DrilldownTarget, InsightSeverity } from "../../lib/analytics/types";
import { ChevronRightIcon, SparklesIcon } from "./icons";
import { AnalyticsSection, Drawer, EmptyState, InfoTip } from "./primitives";

const SEVERITY_LEVEL: Record<InsightSeverity, string> = {
  action_needed: "risk",
  watch: "attention",
  positive: "positive",
  informational: "neutral",
};

const TOP_COUNT = 3;

export function InsightsSection({
  insights,
  sectionId,
  hasData,
  onDrilldown,
}: {
  insights: Insight[];
  sectionId: string;
  hasData: boolean;
  onDrilldown: (target: DrilldownTarget) => void;
}) {
  const narration = useInsightNarration(insights);
  const [openInsightId, setOpenInsightId] = useState<string | null>(null);
  const [showAll, setShowAll] = useState(false);

  const top = insights.slice(0, TOP_COUNT);
  const remaining = insights.length - top.length;
  const openInsight = insights.find((insight) => insight.id === openInsightId) ?? null;

  return (
    <AnalyticsSection
      id={sectionId}
      eyebrow="What stands out"
      title={
        <span className="fb-an-title-with-icon">
          <SparklesIcon size={16} />
          AI Insights
        </span>
      }
      actions={
        insights.length > TOP_COUNT ? (
          <button type="button" className="fb-an-view-link" onClick={() => setShowAll(true)}>
            View all ({insights.length})
          </button>
        ) : (
          <InfoTip
            label="How insights are produced"
            text={
              "Each insight comes from a fixed calculation over your transactions for the selected period. " +
              "The supporting figures are shown with every insight. Language may be rephrased for readability, " +
              "but no total, comparison or conclusion is ever generated by a language model."
            }
          />
        )
      }
    >
      {insights.length === 0 ? (
        <EmptyState
          title={hasData ? "Nothing needs your attention right now" : "No insights yet"}
          message={
            hasData
              ? "Hallix checked reconciliation, receipts, spending changes, vendors, budgets, cash and 2% activity for this period and found nothing worth flagging."
              : "Once the department records transactions and connects or enters its accounts, Hallix will start pointing out what needs attention."
          }
        />
      ) : (
        <>
          <ul className="fb-an-insight-rows">
            {top.map((insight) => (
              <li key={insight.id}>
                <button
                  type="button"
                  className="fb-an-insight-row"
                  onClick={() => setOpenInsightId(insight.id)}
                  aria-haspopup="dialog"
                >
                  <span className={`fb-an-status fb-an-status--${SEVERITY_LEVEL[insight.severity]} fb-an-status--sm`}>
                    <span className="fb-an-status-dot" aria-hidden="true" />
                    {INSIGHT_SEVERITY_LABELS[insight.severity]}
                  </span>
                  <span className="fb-an-insight-row-body">
                    <span className="fb-an-insight-row-title">{insight.title}</span>
                    <span className="fb-an-insight-row-sub">
                      {narration.get(insight.id) ?? insight.summary}
                    </span>
                  </span>
                  <span className="fb-an-insight-row-chevron" aria-hidden="true">
                    <ChevronRightIcon size={16} />
                  </span>
                </button>
              </li>
            ))}
          </ul>

          {remaining > 0 ? (
            <button type="button" className="fb-an-view-link fb-an-insight-more" onClick={() => setShowAll(true)}>
              View all insights ({remaining} more)
            </button>
          ) : null}
        </>
      )}

      {openInsight ? (
        <Drawer
          title={openInsight.title}
          eyebrow={INSIGHT_SEVERITY_LABELS[openInsight.severity]}
          onClose={() => setOpenInsightId(null)}
          footer={
            openInsight.drilldown ? (
              <button
                type="button"
                className="fb-primary-btn"
                onClick={() => onDrilldown(openInsight.drilldown as DrilldownTarget)}
              >
                {openInsight.actionLabel ?? "View the records"}
              </button>
            ) : null
          }
        >
          <InsightDetailBody insight={openInsight} narration={narration} />
        </Drawer>
      ) : null}

      {showAll ? (
        <Drawer title="All insights" eyebrow="What stands out" onClose={() => setShowAll(false)}>
          <ul className="fb-an-insight-rows">
            {insights.map((insight) => (
              <li key={insight.id} className="fb-an-component">
                <details>
                  <summary className="fb-an-insight-detail-head">
                    <span className={`fb-an-status fb-an-status--${SEVERITY_LEVEL[insight.severity]} fb-an-status--sm`}>
                      <span className="fb-an-status-dot" aria-hidden="true" />
                      {INSIGHT_SEVERITY_LABELS[insight.severity]}
                    </span>
                    <strong>{insight.title}</strong>
                  </summary>
                  <InsightDetailBody insight={insight} narration={narration} />
                  {insight.drilldown ? (
                    <button
                      type="button"
                      className="fb-secondary-btn"
                      onClick={() => onDrilldown(insight.drilldown as DrilldownTarget)}
                    >
                      {insight.actionLabel ?? "View the records"}
                    </button>
                  ) : null}
                </details>
              </li>
            ))}
          </ul>
        </Drawer>
      ) : null}
    </AnalyticsSection>
  );
}

function InsightDetailBody({
  insight,
  narration,
}: {
  insight: Insight;
  narration: Map<string, string>;
}) {
  return (
    <>
      <p className="fb-an-insight-summary">{narration.get(insight.id) ?? insight.summary}</p>

      <dl className="fb-an-citations">
        {insight.citations.map((citation) => (
          <div key={citation.label} className="fb-an-citation">
            <dt>{citation.label}</dt>
            <dd>{citation.value}</dd>
          </div>
        ))}
      </dl>

      {insight.comparisonLabel ? (
        <p className="muted fb-an-insight-compare">Compared with {insight.comparisonLabel}</p>
      ) : null}

      <p className="fb-an-insight-action">
        <strong>Next step:</strong> {insight.recommendedAction}
      </p>

      <p className="muted fb-an-footnote">{insight.method}</p>
    </>
  );
}

/**
 * Requests plainer wording for the already-computed insights.
 *
 * Failures are deliberately silent: the deterministic summary is already
 * correct and readable, so a missing API key or a slow model should not surface
 * an error to a treasurer.
 */
function useInsightNarration(insights: Insight[]): Map<string, string> {
  const [narration, setNarration] = useState<Map<string, string>>(new Map());
  const requestedRef = useRef<string>("");

  useEffect(() => {
    if (insights.length === 0) {
      setNarration(new Map());
      return;
    }

    const payload = insightNarrationPayload(insights);
    const signature = JSON.stringify(payload);
    if (requestedRef.current === signature) return;
    requestedRef.current = signature;

    const controller = new AbortController();
    let cancelled = false;

    void (async () => {
      try {
        const response = await fetch("/api/analytics/insight-narrative", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ insights: payload }),
          signal: controller.signal,
        });
        if (!response.ok) return;

        const body = (await response.json()) as { summaries?: Array<{ id: string; summary: string }> };
        if (cancelled || !Array.isArray(body.summaries)) return;

        const allowedIds = new Set(insights.map((insight) => insight.id));
        const next = new Map<string, string>();
        for (const entry of body.summaries) {
          if (!allowedIds.has(entry.id)) continue;
          if (typeof entry.summary !== "string") continue;
          const trimmed = entry.summary.trim();
          if (trimmed.length === 0 || trimmed.length > 400) continue;
          next.set(entry.id, trimmed);
        }
        if (next.size > 0) setNarration(next);
      } catch {
        // Deterministic wording is already on screen; nothing to recover from.
      }
    })();

    return () => {
      cancelled = true;
      controller.abort();
    };
  }, [insights]);

  return narration;
}
